language: python
python:
  - "2.7"

services:
 - postgresql
 - memcached

virtualenv:
  system_site_packages: true

env:
  - DJANGO_DB_USER=postgres DJANGO_SETTINGS_MODULE=settings PYLINT=N PYTHONPATH=

before_install:
 - psql -c 'create database amcat;' -U postgres

install: 
 - sudo apt-get update
 - cat apt_requirements.txt | tr '\n' ' ' | xargs sudo apt-get install -y
 - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.5.deb
 - sudo dpkg -i ./elasticsearch-0.90.5.deb
 - rm ./elasticsearch-0.90.5.deb
 - pip install -r ./pip_requirements.txt --use-mirrors

script:
 - python ./manage.py test amcat
 - python ./manage.py test navigator
