language: python
python:
  - "2.7"

services:
 - postgresql
 - memcached

virtualenv:
  system_site_packages: true

before_install:
 - sudo apt-get install -qq `cat apt_requirements.txt | tr '\n' ' '`
 - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.5.deb
 - sudo dpkg -i ./elasticsearch-0.90.5.deb
 - rm ./elasticsearch-0.90.5.deb

install: 
 - pip install -r ./pip_requirements.txt --use-mirrors

script:
 - DJANGO_DB_USER=postgres ./manage.py test amcat
 - DJANGO_DB_USER=postgres ./manage.py test navigator
