language: python
python:
  - "2.7"

services:
 - postgresql
 - memcached
 - rabbitmq

virtualenv:
  system_site_packages: true

before_install:
 - psql -c 'create database amcat;' -U postgres
 - export DJANGO_DB_USER=postgres
 - export DJANGO_LOG_LEVEL=WARNING
 - export DJANGO_SETTINGS_MODULE=settings
 - export PYTHONPATH=

install:
 - sudo apt-get update
 - cat apt_requirements.txt | tr '\n' ' ' | xargs sudo apt-get install -y
 - sudo service rabbitmq-server start
 - wget http://hmbastiaan.nl/martijn/amcat/hitcount.jar
 - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.3.1.tar.gz -O - | tar xvz
 - cd elasticsearch-1*
 - bin/plugin -install elasticsearch/elasticsearch-lang-python/2.3.0
 - bin/plugin -install elasticsearch/elasticsearch-analysis-icu/2.3.0
 - bin/plugin -install mobz/elasticsearch-head
 - cd ..
 - ES_CLASSPATH=hitcount.jar elasticsearch-1*/bin/elasticsearch -Des.index.similarity.default.type=nl.vu.amcat.HitCountSimilarityProvider -d
 - pip install -r requirements.txt
 - pip install coverage coveralls

script:
 - coverage run --source=. --omit=*/migrations/*,settings/* -m amcat.manage test

after_success:
 - coverage report -m
 - coveralls