language: python
python:
  - "2.7"

services:
 - postgresql
 - memcached
 - rabbitmq

virtualenv:
  system_site_packages: true

env:
  - SUITE=api
  - SUITE=accounts
  - SUITE=annotator
  - SUITE=amcat
  - SUITE=navigator

before_install:
 - psql -c 'create database amcat;' -U postgres
 - export DJANGO_DB_USER=postgres
 - export DJANGO_LOG_LEVEL=WARNING
 - export DJANGO_SETTINGS_MODULE=settings
 - export PYLINT=N
 - export PYTHONPATH=

install: 
 - sudo apt-get update
 - cat apt_requirements.txt | tr '\n' ' ' | xargs sudo apt-get install -y
 - curl https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.5.tar.gz  | tar xvz
 - wget http://amcat.vu.nl/plain/hitcount.jar
 - elasticsearch-0.90.5/bin/plugin -install elasticsearch/elasticsearch-lang-python/1.2.0
 - ES_CLASSPATH=hitcount.jar elasticsearch-0.90.5/bin/elasticsearch -Des.index.similarity.default.type=nl.vu.amcat.HitCountSimilarityProvider
 - pip install -r ./pip_requirements.txt --use-mirrors 

script:
 - python ./manage.py test $SUITE
